import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath, URL } from 'node:url'

import vue from '@vitejs/plugin-vue'
import { defineConfig, loadEnv } from 'vite'

// Locally-trusted dev certs generated by `make certs`. Falls
// back to plain HTTP if they haven't been generated yet.
const certFile = fileURLToPath(new URL('../certs/localhost.pem', import.meta.url))
const keyFile = fileURLToPath(new URL('../certs/localhost-key.pem', import.meta.url))
const httpsOptions =
  existsSync(certFile) && existsSync(keyFile)
    ? { cert: readFileSync(certFile), key: readFileSync(keyFile) }
    : undefined

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '')
  const proxyTarget = env.VITE_API_PROXY_TARGET || 'https://localhost:8080'

  return {
    plugins: [vue()],
    resolve: {
      alias: {
        '@': fileURLToPath(new URL('./src', import.meta.url)),
      },
    },
    server: {
      https: httpsOptions,
      proxy: {
        '/api': {
          target: proxyTarget,
          changeOrigin: true,
          // The backend uses the same locally-trusted mkcert cert, but
          // Node's proxy client doesn't share the OS/browser trust store.
          secure: false,
        },
        '/uploads': {
          target: proxyTarget,
          changeOrigin: true,
          secure: false,
        },
      },
    },
  }
})
