{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "penates.fullname" . }}
  labels:
    {{- include "penates.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "penates.selectorLabels" . | nindent 6 }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
{{- end }}
