{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "penates.postgresSecretName" . }}
  labels:
    {{- include "penates.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
data:
  {{ .Values.postgres.auth.secretKeys.adminPasswordKey | default "postgres-password" }}: {{ .Values.postgres.auth.password | b64enc | quote }}
{{- end }}
