{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "penates.serviceAccountName" . }}
  labels:
    {{- include "penates.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{/*
Create service account name
*/}}
{{- define "penates.serviceAccountName" -}}
{{- default (include "penates.fullname" .) .Values.serviceAccount.name -}}
{{- end -}}
